[package]
name = "itasca"
version = "0.1.0"
edition = "2021"
description = "Formally verified WebAssembly 1.0 module validator"
license = "MIT OR Apache-2.0"
repository = "https://github.com/eqrion/itasca"
include = [
    "src/**/*",
    "/Cargo.toml",
    "/README.md",
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
]

[features]
default = ["std"]
std = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(charon)'] }

[dev-dependencies]
wasmparser = "=0.252.0"
wast = "=252.0.0"
wasm-smith = "=0.252.0"
arbitrary = "1"
anyhow = "1"
