# Verification pipeline: Rust -> Charon -> LLBC -> Aeneas -> Coq
#
# Usage:
#   make build      Build the Rust library
#   make test       Run Rust tests
#   make llbc       Extract LLBC via Charon
#   make coq        Generate Coq code via Aeneas
#   make check-coq  Compile the extraction only, skipping the proofs
#   make prove      Compile all Coq files
#   make all        Full pipeline
#   make clean      Remove all generated artifacts
#
# Coq compilation is delegated to Makefile.coq, generated by coq_makefile from
# _CoqProject. Register new theory files in _CoqProject, not here.
#
# Override tool paths: make CHARON=/path/to/charon AENEAS=/path/to/aeneas

AENEAS_DIR ?= $(dir $(abspath $(lastword $(MAKEFILE_LIST))))vendor/aeneas
# Two switches: Coq and the proofs live in one, Aeneas itself builds in the
# other, which is on a newer OCaml.
OPAM_SWITCH ?= wasmcert
AENEAS_SWITCH ?= aeneas
OPAM_PREFIX := $(shell opam var prefix --switch=$(OPAM_SWITCH) 2>/dev/null)
NPROC := $(shell nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

CARGO  ?= cargo
CHARON ?= $(AENEAS_DIR)/charon/bin/charon
AENEAS ?= $(AENEAS_DIR)/src/_build/install/default/bin/aeneas

WASMCERT_VO = vendor/WasmCert-Coq/_build/default/theories

LLBC_FILE = veriwasm.llbc
RUST_SOURCES = $(shell find src -name '*.rs')

# COQBIN needs the trailing slash here: Makefile.coq would add one itself, but
# variables set on the make command line override in-makefile assignments.
# -j$(NPROC): the theory files form a real dependency DAG, not a chain, so
# coqc processes overlap instead of running one at a time.
MAKE_COQ = $(MAKE) -f Makefile.coq COQBIN=$(OPAM_PREFIX)/bin/ -j$(NPROC)

# Apply a patch to a vendored checkout, tolerating one that is already applied
# so the recipe can rerun. $(1) = checkout dir, $(2) = patch, repo-relative.
apply_patch = cd $(1) && { git apply --reverse --check $(CURDIR)/$(2) 2>/dev/null \
		|| git apply $(CURDIR)/$(2); }

.PHONY: all build test llbc aeneas coq check-coq prove check-wasmcert clean

all: test prove

# --- Rust ---

build:
	$(CARGO) build

test: build
	$(CARGO) test

# --- Charon: Rust -> LLBC ---

llbc: $(LLBC_FILE)

$(LLBC_FILE): $(RUST_SOURCES) Cargo.toml Charon.toml
	$(CHARON) cargo --preset=aeneas

# --- Aeneas: LLBC -> Coq ---
# Every function in src/ has to translate, so an Aeneas error fails the build.
# It used not to: src/binary/ was opaque because its reader held a borrow, and
# the recipe ignored the exit code to get past it. That also meant a genuine
# translation error left a truncated .v behind and said nothing.

AENEAS_GENERATED = theories/Veriwasm_Types.v theories/Veriwasm_Funs.v
AENEAS_PATCHES = patches/aeneas-coq-tuple-binder.patch \
		 patches/aeneas-coq-slice-index-clash.patch

aeneas: $(AENEAS)

$(AENEAS): $(AENEAS_PATCHES)
	$(foreach p,$(AENEAS_PATCHES),$(call apply_patch,$(AENEAS_DIR),$(p));)
	cd $(AENEAS_DIR)/src && eval $$(opam env --switch=$(AENEAS_SWITCH)) && dune build

coq: $(AENEAS_GENERATED)

$(AENEAS_GENERATED): $(LLBC_FILE) $(AENEAS)
	$(AENEAS) -backend coq $(LLBC_FILE) -dest theories/ -split-files

# --- Coq compilation ---

prove: Makefile.coq $(WASMCERT_VO)/type_checker.vo
	$(MAKE_COQ)

check-coq: Makefile.coq
	$(MAKE_COQ) theories/Veriwasm_Funs.vo

Makefile.coq: _CoqProject
	$(OPAM_PREFIX)/bin/coq_makefile -f _CoqProject -o $@

# --- WasmCert-Coq ---
# The submodule stays on canonical upstream; the Coq version bound is relaxed
# by a patch. See patches/wasmcert-coq-8.18.patch.

WASMCERT_PATCH = patches/wasmcert-coq-8.18.patch

check-wasmcert: $(WASMCERT_VO)/type_checker.vo

$(WASMCERT_VO)/type_checker.vo: $(WASMCERT_PATCH)
	$(call apply_patch,vendor/WasmCert-Coq,$(WASMCERT_PATCH))
	cd vendor/WasmCert-Coq && eval $$(opam env --switch=$(OPAM_SWITCH)) && dune build theories/

# --- Clean ---

clean:
	-$(MAKE_COQ) cleanall
	rm -f Makefile.coq Makefile.coq.conf .Makefile.coq.d
	rm -f $(LLBC_FILE)
	rm -f $(AENEAS_GENERATED) theories/*_Template.v
	rm -f .lia.cache theories/.lia.cache
	$(CARGO) clean
