(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [itasca]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Itasca_Types.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq] *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
  core_cmp_PartialEq_t_ne : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.
Arguments core_cmp_PartialEq_t_ne { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq] *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible] *)
Inductive core_convert_Infallible_t :=.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow] *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result] *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [itasca::types::ValueType]
    Source: 'src/types.rs', lines 12:0-17:1 *)
Inductive types_ValueType_t :=
| Types_ValueType_I32 : types_ValueType_t
| Types_ValueType_I64 : types_ValueType_t
| Types_ValueType_F32 : types_ValueType_t
| Types_ValueType_F64 : types_ValueType_t
.

(** [itasca::code::BlockType]
    Source: 'src/code.rs', lines 39:0-42:1 *)
Inductive code_BlockType_t :=
| Code_BlockType_Empty : code_BlockType_t
| Code_BlockType_Value : types_ValueType_t -> code_BlockType_t
.

(** [itasca::code::MemArg]
    Source: 'src/code.rs', lines 59:0-62:1 *)
Record code_MemArg_t :=
mkcode_MemArg_t {
  code_MemArg_align : u32; code_MemArg_offset : u32;
}
.

(** [itasca::code::LocalsStack]
    Source: 'src/code.rs', lines 313:0-317:1 *)
Record code_LocalsStack_t :=
mkcode_LocalsStack_t {
  code_LocalsStack_inline : array types_ValueType_t 32%usize;
  code_LocalsStack_overflow : alloc_vec_Vec types_ValueType_t;
  code_LocalsStack_inline_len : usize;
}
.

(** [itasca::code::Context]
    Source: 'src/code.rs', lines 73:0-81:1 *)
Record code_Context_t :=
mkcode_Context_t {
  code_Context_locals : code_LocalsStack_t;
  code_Context_results : option types_ValueType_t;
}
.

(** [itasca::error::VisitError]
    Source: 'src/error.rs', lines 50:0-52:1 *)
Inductive error_VisitError_t :=
| Error_VisitError_OutOfMemory : error_VisitError_t
.

(** [itasca::error::OpError]
    Source: 'src/error.rs', lines 18:0-45:1 *)
Inductive error_OpError_t :=
| Error_OpError_UnexpectedEof : error_OpError_t
| Error_OpError_LebTooLong : error_OpError_t
| Error_OpError_UnrecognizedOpcode : error_OpError_t
| Error_OpError_InvalidBlockType : error_OpError_t
| Error_OpError_TypeMismatch : error_OpError_t
| Error_OpError_EmptyStack : error_OpError_t
| Error_OpError_StackMismatch : error_OpError_t
| Error_OpError_UnknownLabel : error_OpError_t
| Error_OpError_UnknownLocal : error_OpError_t
| Error_OpError_UnknownGlobal : error_OpError_t
| Error_OpError_ImmutableGlobal : error_OpError_t
| Error_OpError_UnknownMemory : error_OpError_t
| Error_OpError_UnknownFunc : error_OpError_t
| Error_OpError_UnknownType : error_OpError_t
| Error_OpError_UnknownTable : error_OpError_t
| Error_OpError_TooManyResults : error_OpError_t
| Error_OpError_ReservedByteNotZero : error_OpError_t
| Error_OpError_InvalidAlignment : error_OpError_t
| Error_OpError_TrailingBytes : error_OpError_t
| Error_OpError_BodyTooLarge : error_OpError_t
| Error_OpError_Visitor : error_VisitError_t -> error_OpError_t
.

(** [itasca::code::StackType]
    Source: 'src/code.rs', lines 101:0-104:1 *)
Inductive code_StackType_t :=
| Code_StackType_Val : types_ValueType_t -> code_StackType_t
| Code_StackType_Bot : code_StackType_t
.

(** [itasca::code::LabelKind]
    Source: 'src/code.rs', lines 110:0-116:1 *)
Inductive code_LabelKind_t :=
| Code_LabelKind_Body : code_LabelKind_t
| Code_LabelKind_Block : code_LabelKind_t
| Code_LabelKind_Loop : code_LabelKind_t
| Code_LabelKind_Then : code_LabelKind_t
| Code_LabelKind_Else : code_LabelKind_t
.

(** [itasca::code::Ctrl]
    Source: 'src/code.rs', lines 121:0-128:1 *)
Record code_Ctrl_t :=
mkcode_Ctrl_t {
  code_Ctrl_kind : code_LabelKind_t;
  code_Ctrl_block_type : code_BlockType_t;
  code_Ctrl_value_stack_base : usize;
  code_Ctrl_polymorphic_base : bool;
}
.

(** [itasca::code::ValsStack]
    Source: 'src/code.rs', lines 145:0-151:1 *)
Record code_ValsStack_t :=
mkcode_ValsStack_t {
  code_ValsStack_inline : array code_StackType_t 32%usize;
  code_ValsStack_overflow : alloc_vec_Vec code_StackType_t;
  code_ValsStack_inline_len : usize;
}
.

(** [itasca::code::CtrlsStack]
    Source: 'src/code.rs', lines 229:0-233:1 *)
Record code_CtrlsStack_t :=
mkcode_CtrlsStack_t {
  code_CtrlsStack_inline : array code_Ctrl_t 16%usize;
  code_CtrlsStack_overflow : alloc_vec_Vec code_Ctrl_t;
  code_CtrlsStack_inline_len : usize;
}
.

(** [itasca::code::OpIterState]
    Source: 'src/code.rs', lines 383:0-387:1 *)
Record code_OpIterState_t :=
mkcode_OpIterState_t {
  code_OpIterState_vals : code_ValsStack_t;
  code_OpIterState_ctrls : code_CtrlsStack_t;
  code_OpIterState_pos : usize;
}
.

(** [itasca::types::Mut]
    Source: 'src/types.rs', lines 36:0-39:1 *)
Inductive types_Mut_t :=
| Types_Mut_Const : types_Mut_t
| Types_Mut_Var : types_Mut_t
.

(** [itasca::types::GlobalType]
    Source: 'src/types.rs', lines 94:0-97:1 *)
Record types_GlobalType_t :=
mktypes_GlobalType_t {
  types_GlobalType_mutability : types_Mut_t;
  types_GlobalType_valtype : types_ValueType_t;
}
.

(** [itasca::types::ElemType]
    Source: 'src/types.rs', lines 79:0-81:1 *)
Inductive types_ElemType_t := | Types_ElemType_FuncRef : types_ElemType_t.

(** [itasca::types::Limits]
    Source: 'src/types.rs', lines 64:0-67:1 *)
Record types_Limits_t :=
mktypes_Limits_t {
  types_Limits_min : u32; types_Limits_max : option u32;
}
.

(** [itasca::types::TableType]
    Source: 'src/types.rs', lines 86:0-89:1 *)
Record types_TableType_t :=
mktypes_TableType_t {
  types_TableType_limits : types_Limits_t;
  types_TableType_elem : types_ElemType_t;
}
.

(** [itasca::types::MemType]
    Source: 'src/types.rs', lines 72:0-74:1 *)
Record types_MemType_t :=
mktypes_MemType_t {
  types_MemType_limits : types_Limits_t;
}
.

(** [itasca::types::FuncType]
    Source: 'src/types.rs', lines 56:0-59:1 *)
Record types_FuncType_t :=
mktypes_FuncType_t {
  types_FuncType_params : alloc_vec_Vec types_ValueType_t;
  types_FuncType_results : alloc_vec_Vec types_ValueType_t;
}
.

(** [itasca::types::ConstExpr]
    Source: 'src/types.rs', lines 116:0-126:1 *)
Inductive types_ConstExpr_t :=
| Types_ConstExpr_I32 : i32 -> types_ConstExpr_t
| Types_ConstExpr_I64 : i64 -> types_ConstExpr_t
| Types_ConstExpr_F32 : u32 -> types_ConstExpr_t
| Types_ConstExpr_F64 : u64 -> types_ConstExpr_t
| Types_ConstExpr_GlobalGet : u32 -> types_ConstExpr_t
.

(** [itasca::module::Element]
    Source: 'src/module.rs', lines 103:0-107:1 *)
Record module_Element_t :=
mkmodule_Element_t {
  module_Element_table_idx : u32;
  module_Element_offset : types_ConstExpr_t;
  module_Element_init : alloc_vec_Vec u32;
}
.

(** [itasca::module::ExportDesc]
    Source: 'src/module.rs', lines 85:0-90:1 *)
Inductive module_ExportDesc_t :=
| Module_ExportDesc_Func : u32 -> module_ExportDesc_t
| Module_ExportDesc_Table : u32 -> module_ExportDesc_t
| Module_ExportDesc_Memory : u32 -> module_ExportDesc_t
| Module_ExportDesc_Global : u32 -> module_ExportDesc_t
.

(** [itasca::module::Export]
    Source: 'src/module.rs', lines 95:0-98:1 *)
Record module_Export_t :=
mkmodule_Export_t {
  module_Export_name : alloc_vec_Vec u8;
  module_Export_desc : module_ExportDesc_t;
}
.

(** [itasca::module::ImportDesc]
    Source: 'src/module.rs', lines 65:0-70:1 *)
Inductive module_ImportDesc_t :=
| Module_ImportDesc_Func : u32 -> module_ImportDesc_t
| Module_ImportDesc_Table : types_TableType_t -> module_ImportDesc_t
| Module_ImportDesc_Memory : types_MemType_t -> module_ImportDesc_t
| Module_ImportDesc_Global : types_GlobalType_t -> module_ImportDesc_t
.

(** [itasca::module::Import]
    Source: 'src/module.rs', lines 76:0-80:1 *)
Record module_Import_t :=
mkmodule_Import_t {
  module_Import_module : alloc_vec_Vec u8;
  module_Import_name : alloc_vec_Vec u8;
  module_Import_desc : module_ImportDesc_t;
}
.

(** [itasca::module::Global]
    Source: 'src/module.rs', lines 57:0-60:1 *)
Record module_Global_t :=
mkmodule_Global_t {
  module_Global_gtype : types_GlobalType_t;
  module_Global_init : types_ConstExpr_t;
}
.

(** [itasca::module::Env]
    Source: 'src/module.rs', lines 119:0-151:1 *)
Record module_Env_t :=
mkmodule_Env_t {
  module_Env_types : alloc_vec_Vec types_FuncType_t;
  module_Env_imports : alloc_vec_Vec module_Import_t;
  module_Env_globals : alloc_vec_Vec module_Global_t;
  module_Env_exports : alloc_vec_Vec module_Export_t;
  module_Env_elements : alloc_vec_Vec module_Element_t;
  module_Env_start : option u32;
  module_Env_func_type_indices : alloc_vec_Vec u32;
  module_Env_func_types : alloc_vec_Vec types_FuncType_t;
  module_Env_table_types : alloc_vec_Vec types_TableType_t;
  module_Env_mem_types : alloc_vec_Vec types_MemType_t;
  module_Env_global_types : alloc_vec_Vec types_GlobalType_t;
  module_Env_num_imported_funcs : usize;
  module_Env_num_imported_globals : usize;
}
.

(** Trait declaration: [itasca::code::OpVisitor]
    Source: 'src/code.rs', lines 2065:0-2230:1 *)
Record code_OpVisitor_t (Self : Type) := mkcode_OpVisitor_t {
  code_OpVisitor_t_on_function_start : Self -> code_Context_t -> u32 -> usize
    -> usize -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_unreachable : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_nop : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_block : Self -> code_OpIterState_t -> code_BlockType_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_loop : Self -> code_OpIterState_t -> code_BlockType_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_if : Self -> code_OpIterState_t -> code_BlockType_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_else : Self -> code_OpIterState_t -> code_BlockType_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_end : Self -> code_OpIterState_t -> code_LabelKind_t ->
    code_BlockType_t -> result ((core_result_Result_t unit error_VisitError_t)
    * Self);
  code_OpVisitor_t_on_br : Self -> code_OpIterState_t -> u32 ->
    code_BlockType_t -> result ((core_result_Result_t unit error_VisitError_t)
    * Self);
  code_OpVisitor_t_on_br_if : Self -> code_OpIterState_t -> u32 ->
    code_BlockType_t -> result ((core_result_Result_t unit error_VisitError_t)
    * Self);
  code_OpVisitor_t_on_br_table_label : Self -> code_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_br_table : Self -> code_OpIterState_t -> u32 ->
    code_BlockType_t -> result ((core_result_Result_t unit error_VisitError_t)
    * Self);
  code_OpVisitor_t_on_return : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_call : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_call_indirect : Self -> code_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_drop : Self -> code_OpIterState_t -> code_StackType_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_select : Self -> code_OpIterState_t -> code_StackType_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_local_get : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_local_set : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_local_tee : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_global_get : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_global_set : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_memory_size : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_memory_grow : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_const : Self -> code_OpIterState_t -> i32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_const : Self -> code_OpIterState_t -> i64 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_const : Self -> code_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_const : Self -> code_OpIterState_t -> u64 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_load : Self -> code_OpIterState_t -> code_MemArg_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_load : Self -> code_OpIterState_t -> code_MemArg_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_load : Self -> code_OpIterState_t -> code_MemArg_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_load : Self -> code_OpIterState_t -> code_MemArg_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_load8_s : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_load8_u : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_load16_s : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i32_load16_u : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i64_load8_s : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_load8_u : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_load16_s : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i64_load16_u : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i64_load32_s : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i64_load32_u : Self -> code_OpIterState_t ->
    code_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  code_OpVisitor_t_on_i32_store : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_store : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_store : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_store : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_store8 : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_store16 : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_store8 : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_store16 : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_store32 : Self -> code_OpIterState_t -> code_MemArg_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_eqz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_eq : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_ne : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_lt_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_lt_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_gt_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_gt_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_le_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_le_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_ge_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_ge_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_eqz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_eq : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_ne : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_lt_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_lt_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_gt_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_gt_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_le_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_le_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_ge_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_ge_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_eq : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_ne : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_lt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_gt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_le : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_ge : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_eq : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_ne : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_lt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_gt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_le : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_ge : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_sub : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_mul : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_div_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_div_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_rem_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_rem_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_and : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_or : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_xor : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_shl : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_shr_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_shr_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_rotl : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_rotr : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_add : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_sub : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_mul : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_div_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_div_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_rem_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_rem_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_and : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_or : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_xor : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_shl : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_shr_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_shr_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_rotl : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_rotr : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_add : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_sub : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_mul : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_div : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_min : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_max : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_copysign : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_add : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_sub : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_mul : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_div : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_min : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_max : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_copysign : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_clz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_ctz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_popcnt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_add : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_clz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_ctz : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_popcnt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_abs : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_neg : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_ceil : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_floor : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_trunc : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_nearest : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_sqrt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_abs : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_neg : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_ceil : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_floor : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_trunc : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_nearest : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_sqrt : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_wrap_i64 : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_trunc_f32_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_trunc_f32_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_trunc_f64_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_trunc_f64_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_extend_i32_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_extend_i32_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_trunc_f32_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_trunc_f32_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_trunc_f64_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_trunc_f64_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_convert_i32_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_convert_i32_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_convert_i64_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_convert_i64_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_demote_f64 : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_convert_i32_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_convert_i32_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_convert_i64_s : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_convert_i64_u : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_promote_f32 : Self -> code_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i32_reinterpret_f32 : Self -> code_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_i64_reinterpret_f64 : Self -> code_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f32_reinterpret_i32 : Self -> code_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  code_OpVisitor_t_on_f64_reinterpret_i64 : Self -> code_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
}.

Arguments mkcode_OpVisitor_t { _ }.
Arguments code_OpVisitor_t_on_function_start { _ } _.
Arguments code_OpVisitor_t_on_unreachable { _ } _.
Arguments code_OpVisitor_t_on_nop { _ } _.
Arguments code_OpVisitor_t_on_block { _ } _.
Arguments code_OpVisitor_t_on_loop { _ } _.
Arguments code_OpVisitor_t_on_if { _ } _.
Arguments code_OpVisitor_t_on_else { _ } _.
Arguments code_OpVisitor_t_on_end { _ } _.
Arguments code_OpVisitor_t_on_br { _ } _.
Arguments code_OpVisitor_t_on_br_if { _ } _.
Arguments code_OpVisitor_t_on_br_table_label { _ } _.
Arguments code_OpVisitor_t_on_br_table { _ } _.
Arguments code_OpVisitor_t_on_return { _ } _.
Arguments code_OpVisitor_t_on_call { _ } _.
Arguments code_OpVisitor_t_on_call_indirect { _ } _.
Arguments code_OpVisitor_t_on_drop { _ } _.
Arguments code_OpVisitor_t_on_select { _ } _.
Arguments code_OpVisitor_t_on_local_get { _ } _.
Arguments code_OpVisitor_t_on_local_set { _ } _.
Arguments code_OpVisitor_t_on_local_tee { _ } _.
Arguments code_OpVisitor_t_on_global_get { _ } _.
Arguments code_OpVisitor_t_on_global_set { _ } _.
Arguments code_OpVisitor_t_on_memory_size { _ } _.
Arguments code_OpVisitor_t_on_memory_grow { _ } _.
Arguments code_OpVisitor_t_on_i32_const { _ } _.
Arguments code_OpVisitor_t_on_i64_const { _ } _.
Arguments code_OpVisitor_t_on_f32_const { _ } _.
Arguments code_OpVisitor_t_on_f64_const { _ } _.
Arguments code_OpVisitor_t_on_i32_load { _ } _.
Arguments code_OpVisitor_t_on_i64_load { _ } _.
Arguments code_OpVisitor_t_on_f32_load { _ } _.
Arguments code_OpVisitor_t_on_f64_load { _ } _.
Arguments code_OpVisitor_t_on_i32_load8_s { _ } _.
Arguments code_OpVisitor_t_on_i32_load8_u { _ } _.
Arguments code_OpVisitor_t_on_i32_load16_s { _ } _.
Arguments code_OpVisitor_t_on_i32_load16_u { _ } _.
Arguments code_OpVisitor_t_on_i64_load8_s { _ } _.
Arguments code_OpVisitor_t_on_i64_load8_u { _ } _.
Arguments code_OpVisitor_t_on_i64_load16_s { _ } _.
Arguments code_OpVisitor_t_on_i64_load16_u { _ } _.
Arguments code_OpVisitor_t_on_i64_load32_s { _ } _.
Arguments code_OpVisitor_t_on_i64_load32_u { _ } _.
Arguments code_OpVisitor_t_on_i32_store { _ } _.
Arguments code_OpVisitor_t_on_i64_store { _ } _.
Arguments code_OpVisitor_t_on_f32_store { _ } _.
Arguments code_OpVisitor_t_on_f64_store { _ } _.
Arguments code_OpVisitor_t_on_i32_store8 { _ } _.
Arguments code_OpVisitor_t_on_i32_store16 { _ } _.
Arguments code_OpVisitor_t_on_i64_store8 { _ } _.
Arguments code_OpVisitor_t_on_i64_store16 { _ } _.
Arguments code_OpVisitor_t_on_i64_store32 { _ } _.
Arguments code_OpVisitor_t_on_i32_eqz { _ } _.
Arguments code_OpVisitor_t_on_i32_eq { _ } _.
Arguments code_OpVisitor_t_on_i32_ne { _ } _.
Arguments code_OpVisitor_t_on_i32_lt_s { _ } _.
Arguments code_OpVisitor_t_on_i32_lt_u { _ } _.
Arguments code_OpVisitor_t_on_i32_gt_s { _ } _.
Arguments code_OpVisitor_t_on_i32_gt_u { _ } _.
Arguments code_OpVisitor_t_on_i32_le_s { _ } _.
Arguments code_OpVisitor_t_on_i32_le_u { _ } _.
Arguments code_OpVisitor_t_on_i32_ge_s { _ } _.
Arguments code_OpVisitor_t_on_i32_ge_u { _ } _.
Arguments code_OpVisitor_t_on_i64_eqz { _ } _.
Arguments code_OpVisitor_t_on_i64_eq { _ } _.
Arguments code_OpVisitor_t_on_i64_ne { _ } _.
Arguments code_OpVisitor_t_on_i64_lt_s { _ } _.
Arguments code_OpVisitor_t_on_i64_lt_u { _ } _.
Arguments code_OpVisitor_t_on_i64_gt_s { _ } _.
Arguments code_OpVisitor_t_on_i64_gt_u { _ } _.
Arguments code_OpVisitor_t_on_i64_le_s { _ } _.
Arguments code_OpVisitor_t_on_i64_le_u { _ } _.
Arguments code_OpVisitor_t_on_i64_ge_s { _ } _.
Arguments code_OpVisitor_t_on_i64_ge_u { _ } _.
Arguments code_OpVisitor_t_on_f32_eq { _ } _.
Arguments code_OpVisitor_t_on_f32_ne { _ } _.
Arguments code_OpVisitor_t_on_f32_lt { _ } _.
Arguments code_OpVisitor_t_on_f32_gt { _ } _.
Arguments code_OpVisitor_t_on_f32_le { _ } _.
Arguments code_OpVisitor_t_on_f32_ge { _ } _.
Arguments code_OpVisitor_t_on_f64_eq { _ } _.
Arguments code_OpVisitor_t_on_f64_ne { _ } _.
Arguments code_OpVisitor_t_on_f64_lt { _ } _.
Arguments code_OpVisitor_t_on_f64_gt { _ } _.
Arguments code_OpVisitor_t_on_f64_le { _ } _.
Arguments code_OpVisitor_t_on_f64_ge { _ } _.
Arguments code_OpVisitor_t_on_i32_sub { _ } _.
Arguments code_OpVisitor_t_on_i32_mul { _ } _.
Arguments code_OpVisitor_t_on_i32_div_s { _ } _.
Arguments code_OpVisitor_t_on_i32_div_u { _ } _.
Arguments code_OpVisitor_t_on_i32_rem_s { _ } _.
Arguments code_OpVisitor_t_on_i32_rem_u { _ } _.
Arguments code_OpVisitor_t_on_i32_and { _ } _.
Arguments code_OpVisitor_t_on_i32_or { _ } _.
Arguments code_OpVisitor_t_on_i32_xor { _ } _.
Arguments code_OpVisitor_t_on_i32_shl { _ } _.
Arguments code_OpVisitor_t_on_i32_shr_s { _ } _.
Arguments code_OpVisitor_t_on_i32_shr_u { _ } _.
Arguments code_OpVisitor_t_on_i32_rotl { _ } _.
Arguments code_OpVisitor_t_on_i32_rotr { _ } _.
Arguments code_OpVisitor_t_on_i64_add { _ } _.
Arguments code_OpVisitor_t_on_i64_sub { _ } _.
Arguments code_OpVisitor_t_on_i64_mul { _ } _.
Arguments code_OpVisitor_t_on_i64_div_s { _ } _.
Arguments code_OpVisitor_t_on_i64_div_u { _ } _.
Arguments code_OpVisitor_t_on_i64_rem_s { _ } _.
Arguments code_OpVisitor_t_on_i64_rem_u { _ } _.
Arguments code_OpVisitor_t_on_i64_and { _ } _.
Arguments code_OpVisitor_t_on_i64_or { _ } _.
Arguments code_OpVisitor_t_on_i64_xor { _ } _.
Arguments code_OpVisitor_t_on_i64_shl { _ } _.
Arguments code_OpVisitor_t_on_i64_shr_s { _ } _.
Arguments code_OpVisitor_t_on_i64_shr_u { _ } _.
Arguments code_OpVisitor_t_on_i64_rotl { _ } _.
Arguments code_OpVisitor_t_on_i64_rotr { _ } _.
Arguments code_OpVisitor_t_on_f32_add { _ } _.
Arguments code_OpVisitor_t_on_f32_sub { _ } _.
Arguments code_OpVisitor_t_on_f32_mul { _ } _.
Arguments code_OpVisitor_t_on_f32_div { _ } _.
Arguments code_OpVisitor_t_on_f32_min { _ } _.
Arguments code_OpVisitor_t_on_f32_max { _ } _.
Arguments code_OpVisitor_t_on_f32_copysign { _ } _.
Arguments code_OpVisitor_t_on_f64_add { _ } _.
Arguments code_OpVisitor_t_on_f64_sub { _ } _.
Arguments code_OpVisitor_t_on_f64_mul { _ } _.
Arguments code_OpVisitor_t_on_f64_div { _ } _.
Arguments code_OpVisitor_t_on_f64_min { _ } _.
Arguments code_OpVisitor_t_on_f64_max { _ } _.
Arguments code_OpVisitor_t_on_f64_copysign { _ } _.
Arguments code_OpVisitor_t_on_i32_clz { _ } _.
Arguments code_OpVisitor_t_on_i32_ctz { _ } _.
Arguments code_OpVisitor_t_on_i32_popcnt { _ } _.
Arguments code_OpVisitor_t_on_i32_add { _ } _.
Arguments code_OpVisitor_t_on_i64_clz { _ } _.
Arguments code_OpVisitor_t_on_i64_ctz { _ } _.
Arguments code_OpVisitor_t_on_i64_popcnt { _ } _.
Arguments code_OpVisitor_t_on_f32_abs { _ } _.
Arguments code_OpVisitor_t_on_f32_neg { _ } _.
Arguments code_OpVisitor_t_on_f32_ceil { _ } _.
Arguments code_OpVisitor_t_on_f32_floor { _ } _.
Arguments code_OpVisitor_t_on_f32_trunc { _ } _.
Arguments code_OpVisitor_t_on_f32_nearest { _ } _.
Arguments code_OpVisitor_t_on_f32_sqrt { _ } _.
Arguments code_OpVisitor_t_on_f64_abs { _ } _.
Arguments code_OpVisitor_t_on_f64_neg { _ } _.
Arguments code_OpVisitor_t_on_f64_ceil { _ } _.
Arguments code_OpVisitor_t_on_f64_floor { _ } _.
Arguments code_OpVisitor_t_on_f64_trunc { _ } _.
Arguments code_OpVisitor_t_on_f64_nearest { _ } _.
Arguments code_OpVisitor_t_on_f64_sqrt { _ } _.
Arguments code_OpVisitor_t_on_i32_wrap_i64 { _ } _.
Arguments code_OpVisitor_t_on_i32_trunc_f32_s { _ } _.
Arguments code_OpVisitor_t_on_i32_trunc_f32_u { _ } _.
Arguments code_OpVisitor_t_on_i32_trunc_f64_s { _ } _.
Arguments code_OpVisitor_t_on_i32_trunc_f64_u { _ } _.
Arguments code_OpVisitor_t_on_i64_extend_i32_s { _ } _.
Arguments code_OpVisitor_t_on_i64_extend_i32_u { _ } _.
Arguments code_OpVisitor_t_on_i64_trunc_f32_s { _ } _.
Arguments code_OpVisitor_t_on_i64_trunc_f32_u { _ } _.
Arguments code_OpVisitor_t_on_i64_trunc_f64_s { _ } _.
Arguments code_OpVisitor_t_on_i64_trunc_f64_u { _ } _.
Arguments code_OpVisitor_t_on_f32_convert_i32_s { _ } _.
Arguments code_OpVisitor_t_on_f32_convert_i32_u { _ } _.
Arguments code_OpVisitor_t_on_f32_convert_i64_s { _ } _.
Arguments code_OpVisitor_t_on_f32_convert_i64_u { _ } _.
Arguments code_OpVisitor_t_on_f32_demote_f64 { _ } _.
Arguments code_OpVisitor_t_on_f64_convert_i32_s { _ } _.
Arguments code_OpVisitor_t_on_f64_convert_i32_u { _ } _.
Arguments code_OpVisitor_t_on_f64_convert_i64_s { _ } _.
Arguments code_OpVisitor_t_on_f64_convert_i64_u { _ } _.
Arguments code_OpVisitor_t_on_f64_promote_f32 { _ } _.
Arguments code_OpVisitor_t_on_i32_reinterpret_f32 { _ } _.
Arguments code_OpVisitor_t_on_i64_reinterpret_f64 { _ } _.
Arguments code_OpVisitor_t_on_f32_reinterpret_i32 { _ } _.
Arguments code_OpVisitor_t_on_f64_reinterpret_i64 { _ } _.

(** [itasca::code::EmptyOpVisitor]
    Source: 'src/code.rs', lines 2234:0-2234:26 *)
Definition code_EmptyOpVisitor_t : Type := unit.

(** [itasca::error::Error]
    Source: 'src/error.rs', lines 57:0-109:1 *)
Inductive error_Error_t :=
| Error_Error_Read : error_OpError_t -> error_Error_t
| Error_Error_InvalidMagic : error_Error_t
| Error_Error_InvalidVersion : error_Error_t
| Error_Error_UnexpectedEof : error_Error_t
| Error_Error_InvalidType : u8 -> error_Error_t
| Error_Error_UnknownSection : u8 -> error_Error_t
| Error_Error_SectionOutOfOrder : error_Error_t
| Error_Error_SectionSizeMismatch : error_Error_t
| Error_Error_FuncCodeMismatch : error_Error_t
| Error_Error_MissingCodeSection : error_Error_t
| Error_Error_InvalidUtf8 : error_Error_t
| Error_Error_UnknownType : u32 -> error_Error_t
| Error_Error_UnknownFunc : u32 -> error_Error_t
| Error_Error_UnknownTable : u32 -> error_Error_t
| Error_Error_UnknownMemory : u32 -> error_Error_t
| Error_Error_UnknownGlobal : u32 -> error_Error_t
| Error_Error_DuplicateExportName : error_Error_t
| Error_Error_LimitsOutOfRange : error_Error_t
| Error_Error_MultipleMemories : error_Error_t
| Error_Error_MultipleTables : error_Error_t
| Error_Error_InvalidStartType : error_Error_t
| Error_Error_MutableGlobalInConstExpr : error_Error_t
| Error_Error_InvalidConstExpr : error_Error_t
| Error_Error_TooManyResults : error_Error_t
| Error_Error_TooManyLocals : error_Error_t
| Error_Error_ModuleTooLarge : error_Error_t
| Error_Error_Body : error_OpError_t -> error_Error_t
| Error_Error_Visitor : error_VisitError_t -> error_Error_t
.

(** [itasca::module::Data]
    Source: 'src/module.rs', lines 182:0-186:1 *)
Record module_Data_t :=
mkmodule_Data_t {
  module_Data_memory_idx : u32;
  module_Data_offset : types_ConstExpr_t;
  module_Data_init : alloc_vec_Vec u8;
}
.

(** [itasca::module::Tail]
    Source: 'src/module.rs', lines 190:0-192:1 *)
Record module_Tail_t :=
mkmodule_Tail_t {
  module_Tail_data : alloc_vec_Vec module_Data_t;
}
.

(** [itasca::module::Module]
    Source: 'src/module.rs', lines 196:0-199:1 *)
Record module_Module_t :=
mkmodule_Module_t {
  module_Module_env : module_Env_t; module_Module_tail : module_Tail_t;
}
.

(** Trait declaration: [itasca::module::CodeVisitor]
    Source: 'src/module.rs', lines 1530:0-1562:1 *)
Record module_CodeVisitor_t (Self : Type) := mkmodule_CodeVisitor_t {
  module_CodeVisitor_t_on_need_bytes : Self -> usize -> result
    ((core_result_Result_t unit error_Error_t) * Self);
  module_CodeVisitor_t_on_code_entry : Self -> slice u8 -> module_Env_t ->
    usize -> usize -> usize -> usize -> result ((core_result_Result_t unit
    error_Error_t) * Self);
}.

Arguments mkmodule_CodeVisitor_t { _ }.
Arguments module_CodeVisitor_t_on_need_bytes { _ } _.
Arguments module_CodeVisitor_t_on_code_entry { _ } _.

(** [itasca::types::CustomSection]
    Source: 'src/types.rs', lines 136:0-144:1 *)
Record types_CustomSection_t :=
mktypes_CustomSection_t {
  types_CustomSection_name_len : usize;
  types_CustomSection_payload_start : usize;
  types_CustomSection_payload_end : usize;
}
.

(** Trait declaration: [itasca::module::ModuleVisitor]
    Source: 'src/module.rs', lines 1486:0-1496:1 *)
Record module_ModuleVisitor_t (Self : Type) := mkmodule_ModuleVisitor_t {
  module_ModuleVisitor_t_on_custom_section : Self -> types_CustomSection_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
}.

Arguments mkmodule_ModuleVisitor_t { _ }.
Arguments module_ModuleVisitor_t_on_custom_section { _ } _.

(** [itasca::module::CodeSection]
    Source: 'src/module.rs', lines 1263:0-1272:1 *)
Record module_CodeSection_t :=
mkmodule_CodeSection_t {
  module_CodeSection_count : u32;
  module_CodeSection_entries : usize;
  module_CodeSection_end : usize;
}
.

(** [itasca::module::EmptyModuleVisitor]
    Source: 'src/module.rs', lines 1500:0-1500:30 *)
Definition module_EmptyModuleVisitor_t : Type := unit.

(** [itasca::module::ValidatingCodeVisitor]
    Source: 'src/module.rs', lines 1567:0-1567:33 *)
Definition module_ValidatingCodeVisitor_t : Type := unit.

(** [itasca::types::ExternType]
    Source: 'src/types.rs', lines 102:0-107:1 *)
Inductive types_ExternType_t :=
| Types_ExternType_Func : types_FuncType_t -> types_ExternType_t
| Types_ExternType_Table : types_TableType_t -> types_ExternType_t
| Types_ExternType_Memory : types_MemType_t -> types_ExternType_t
| Types_ExternType_Global : types_GlobalType_t -> types_ExternType_t
.

End Itasca_Types.
