(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [veriwasm]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Veriwasm_Types.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq] *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
  core_cmp_PartialEq_t_ne : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.
Arguments core_cmp_PartialEq_t_ne { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq] *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible] *)
Inductive core_convert_Infallible_t :=.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow] *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result] *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [veriwasm::types::ConstExpr]
    Source: 'src/types.rs', lines 100:0-110:1 *)
Inductive types_ConstExpr_t :=
| Types_ConstExpr_I32 : i32 -> types_ConstExpr_t
| Types_ConstExpr_I64 : i64 -> types_ConstExpr_t
| Types_ConstExpr_F32 : u32 -> types_ConstExpr_t
| Types_ConstExpr_F64 : u64 -> types_ConstExpr_t
| Types_ConstExpr_GlobalGet : u32 -> types_ConstExpr_t
.

(** [veriwasm::types::Mut]
    Source: 'src/types.rs', lines 38:0-41:1 *)
Inductive types_Mut_t :=
| Types_Mut_Const : types_Mut_t
| Types_Mut_Var : types_Mut_t
.

(** [veriwasm::types::ValueType]
    Source: 'src/types.rs', lines 14:0-19:1 *)
Inductive types_ValueType_t :=
| Types_ValueType_I32 : types_ValueType_t
| Types_ValueType_I64 : types_ValueType_t
| Types_ValueType_F32 : types_ValueType_t
| Types_ValueType_F64 : types_ValueType_t
.

(** [veriwasm::types::GlobalType]
    Source: 'src/types.rs', lines 88:0-91:1 *)
Record types_GlobalType_t :=
mktypes_GlobalType_t {
  types_GlobalType_mutability : types_Mut_t;
  types_GlobalType_valtype : types_ValueType_t;
}
.

(** [veriwasm::env::Global]
    Source: 'src/env.rs', lines 20:0-23:1 *)
Record env_Global_t :=
mkenv_Global_t {
  env_Global_gtype : types_GlobalType_t; env_Global_init : types_ConstExpr_t;
}
.

(** [veriwasm::types::ElemType]
    Source: 'src/types.rs', lines 73:0-75:1 *)
Inductive types_ElemType_t := | Types_ElemType_FuncRef : types_ElemType_t.

(** [veriwasm::limits::Limits]
    Source: 'src/limits.rs', lines 53:0-56:1 *)
Record limits_Limits_t :=
mklimits_Limits_t {
  limits_Limits_min : u32; limits_Limits_max : option u32;
}
.

(** [veriwasm::types::TableType]
    Source: 'src/types.rs', lines 80:0-83:1 *)
Record types_TableType_t :=
mktypes_TableType_t {
  types_TableType_limits : limits_Limits_t;
  types_TableType_elem : types_ElemType_t;
}
.

(** [veriwasm::types::MemType]
    Source: 'src/types.rs', lines 66:0-68:1 *)
Record types_MemType_t :=
mktypes_MemType_t {
  types_MemType_limits : limits_Limits_t;
}
.

(** [veriwasm::env::ImportDesc]
    Source: 'src/env.rs', lines 28:0-33:1 *)
Inductive env_ImportDesc_t :=
| Env_ImportDesc_Func : u32 -> env_ImportDesc_t
| Env_ImportDesc_Table : types_TableType_t -> env_ImportDesc_t
| Env_ImportDesc_Memory : types_MemType_t -> env_ImportDesc_t
| Env_ImportDesc_Global : types_GlobalType_t -> env_ImportDesc_t
.

(** [veriwasm::env::Import]
    Source: 'src/env.rs', lines 40:0-44:1 *)
Record env_Import_t :=
mkenv_Import_t {
  env_Import_module : alloc_vec_Vec u8;
  env_Import_name : alloc_vec_Vec u8;
  env_Import_desc : env_ImportDesc_t;
}
.

(** [veriwasm::env::ExportDesc]
    Source: 'src/env.rs', lines 49:0-54:1 *)
Inductive env_ExportDesc_t :=
| Env_ExportDesc_Func : u32 -> env_ExportDesc_t
| Env_ExportDesc_Table : u32 -> env_ExportDesc_t
| Env_ExportDesc_Memory : u32 -> env_ExportDesc_t
| Env_ExportDesc_Global : u32 -> env_ExportDesc_t
.

(** [veriwasm::env::Export]
    Source: 'src/env.rs', lines 59:0-62:1 *)
Record env_Export_t :=
mkenv_Export_t {
  env_Export_name : alloc_vec_Vec u8; env_Export_desc : env_ExportDesc_t;
}
.

(** [veriwasm::env::Element]
    Source: 'src/env.rs', lines 67:0-71:1 *)
Record env_Element_t :=
mkenv_Element_t {
  env_Element_table_idx : u32;
  env_Element_offset : types_ConstExpr_t;
  env_Element_init : alloc_vec_Vec u32;
}
.

(** [veriwasm::types::FuncType]
    Source: 'src/types.rs', lines 58:0-61:1 *)
Record types_FuncType_t :=
mktypes_FuncType_t {
  types_FuncType_params : alloc_vec_Vec types_ValueType_t;
  types_FuncType_results : alloc_vec_Vec types_ValueType_t;
}
.

(** [veriwasm::env::Env]
    Source: 'src/env.rs', lines 76:0-108:1 *)
Record env_Env_t :=
mkenv_Env_t {
  env_Env_types : alloc_vec_Vec types_FuncType_t;
  env_Env_imports : alloc_vec_Vec env_Import_t;
  env_Env_globals : alloc_vec_Vec env_Global_t;
  env_Env_exports : alloc_vec_Vec env_Export_t;
  env_Env_elements : alloc_vec_Vec env_Element_t;
  env_Env_start : option u32;
  env_Env_func_type_indices : alloc_vec_Vec u32;
  env_Env_func_types : alloc_vec_Vec types_FuncType_t;
  env_Env_table_types : alloc_vec_Vec types_TableType_t;
  env_Env_mem_types : alloc_vec_Vec types_MemType_t;
  env_Env_global_types : alloc_vec_Vec types_GlobalType_t;
  env_Env_num_imported_funcs : usize;
  env_Env_num_imported_globals : usize;
}
.

(** [veriwasm::error::OpError]
    Source: 'src/error.rs', lines 19:0-44:1 *)
Inductive error_OpError_t :=
| Error_OpError_UnexpectedEof : error_OpError_t
| Error_OpError_LebTooLong : error_OpError_t
| Error_OpError_UnrecognizedOpcode : error_OpError_t
| Error_OpError_InvalidBlockType : error_OpError_t
| Error_OpError_TypeMismatch : error_OpError_t
| Error_OpError_EmptyStack : error_OpError_t
| Error_OpError_StackMismatch : error_OpError_t
| Error_OpError_UnknownLabel : error_OpError_t
| Error_OpError_UnknownLocal : error_OpError_t
| Error_OpError_UnknownGlobal : error_OpError_t
| Error_OpError_ImmutableGlobal : error_OpError_t
| Error_OpError_UnknownMemory : error_OpError_t
| Error_OpError_UnknownFunc : error_OpError_t
| Error_OpError_UnknownType : error_OpError_t
| Error_OpError_UnknownTable : error_OpError_t
| Error_OpError_TooManyResults : error_OpError_t
| Error_OpError_ReservedByteNotZero : error_OpError_t
| Error_OpError_InvalidAlignment : error_OpError_t
| Error_OpError_ProtocolViolation : error_OpError_t
| Error_OpError_TrailingBytes : error_OpError_t
| Error_OpError_BodyTooLarge : error_OpError_t
.

(** [veriwasm::error::Error]
    Source: 'src/error.rs', lines 49:0-90:1 *)
Inductive error_Error_t :=
| Error_Error_Read : error_OpError_t -> error_Error_t
| Error_Error_InvalidMagic : error_Error_t
| Error_Error_InvalidVersion : error_Error_t
| Error_Error_UnexpectedEof : error_Error_t
| Error_Error_InvalidType : u8 -> error_Error_t
| Error_Error_UnknownSection : u8 -> error_Error_t
| Error_Error_SectionOutOfOrder : error_Error_t
| Error_Error_SectionSizeMismatch : error_Error_t
| Error_Error_FuncCodeMismatch : error_Error_t
| Error_Error_InvalidUtf8 : error_Error_t
| Error_Error_UnknownType : u32 -> error_Error_t
| Error_Error_UnknownFunc : u32 -> error_Error_t
| Error_Error_UnknownTable : u32 -> error_Error_t
| Error_Error_UnknownMemory : u32 -> error_Error_t
| Error_Error_UnknownGlobal : u32 -> error_Error_t
| Error_Error_DuplicateExportName : error_Error_t
| Error_Error_LimitsOutOfRange : error_Error_t
| Error_Error_MultipleMemories : error_Error_t
| Error_Error_MultipleTables : error_Error_t
| Error_Error_InvalidStartType : error_Error_t
| Error_Error_MutableGlobalInConstExpr : error_Error_t
| Error_Error_InvalidConstExpr : error_Error_t
| Error_Error_TooManyResults : error_Error_t
| Error_Error_TooManyLocals : error_Error_t
| Error_Error_ModuleTooLarge : error_Error_t
| Error_Error_Body : error_OpError_t -> error_Error_t
.

(** [veriwasm::module::Data]
    Source: 'src/module.rs', lines 52:0-56:1 *)
Record module_Data_t :=
mkmodule_Data_t {
  module_Data_memory_idx : u32;
  module_Data_offset : types_ConstExpr_t;
  module_Data_init : alloc_vec_Vec u8;
}
.

(** [veriwasm::module::Tail]
    Source: 'src/module.rs', lines 60:0-62:1 *)
Record module_Tail_t :=
mkmodule_Tail_t {
  module_Tail_data : alloc_vec_Vec module_Data_t;
}
.

(** [veriwasm::module::ValidatedModule]
    Source: 'src/module.rs', lines 66:0-69:1 *)
Record module_ValidatedModule_t :=
mkmodule_ValidatedModule_t {
  module_ValidatedModule_env : env_Env_t;
  module_ValidatedModule_tail : module_Tail_t;
}
.

(** [veriwasm::opiter::LabelKind]
    Source: 'src/opiter.rs', lines 83:0-89:1 *)
Inductive opiter_LabelKind_t :=
| Opiter_LabelKind_Body : opiter_LabelKind_t
| Opiter_LabelKind_Block : opiter_LabelKind_t
| Opiter_LabelKind_Loop : opiter_LabelKind_t
| Opiter_LabelKind_Then : opiter_LabelKind_t
| Opiter_LabelKind_Else : opiter_LabelKind_t
.

(** [veriwasm::opiter::BlockType]
    Source: 'src/opiter.rs', lines 28:0-31:1 *)
Inductive opiter_BlockType_t :=
| Opiter_BlockType_Empty : opiter_BlockType_t
| Opiter_BlockType_Value : types_ValueType_t -> opiter_BlockType_t
.

(** [veriwasm::opiter::Ctrl]
    Source: 'src/opiter.rs', lines 94:0-101:1 *)
Record opiter_Ctrl_t :=
mkopiter_Ctrl_t {
  opiter_Ctrl_kind : opiter_LabelKind_t;
  opiter_Ctrl_block_type : opiter_BlockType_t;
  opiter_Ctrl_value_stack_base : usize;
  opiter_Ctrl_polymorphic_base : bool;
}
.

(** [veriwasm::opiter::StackType]
    Source: 'src/opiter.rs', lines 74:0-77:1 *)
Inductive opiter_StackType_t :=
| Opiter_StackType_Val : types_ValueType_t -> opiter_StackType_t
| Opiter_StackType_Bot : opiter_StackType_t
.

(** [veriwasm::opiter::OpIterState]
    Source: 'src/opiter.rs', lines 106:0-114:1 *)
Record opiter_OpIterState_t :=
mkopiter_OpIterState_t {
  opiter_OpIterState_vals : alloc_vec_Vec opiter_StackType_t;
  opiter_OpIterState_ctrls : alloc_vec_Vec opiter_Ctrl_t;
  opiter_OpIterState_pos : usize;
  opiter_OpIterState_pending : option u8;
}
.

(** [veriwasm::opiter::MemArg]
    Source: 'src/opiter.rs', lines 48:0-51:1 *)
Record opiter_MemArg_t :=
mkopiter_MemArg_t {
  opiter_MemArg_align : u32; opiter_MemArg_offset : u32;
}
.

(** [veriwasm::opiter::Context]
    Source: 'src/opiter.rs', lines 57:0-61:1 *)
Record opiter_Context_t :=
mkopiter_Context_t {
  opiter_Context_locals : alloc_vec_Vec types_ValueType_t;
  opiter_Context_results : alloc_vec_Vec types_ValueType_t;
}
.

End Veriwasm_Types.
