(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [veriwasm]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Veriwasm_Types.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq] *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
  core_cmp_PartialEq_t_ne : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.
Arguments core_cmp_PartialEq_t_ne { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq] *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible] *)
Inductive core_convert_Infallible_t :=.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow] *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result] *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [veriwasm::types::ConstExpr]
    Source: 'src/types.rs', lines 110:0-120:1 *)
Inductive types_ConstExpr_t :=
| Types_ConstExpr_I32 : i32 -> types_ConstExpr_t
| Types_ConstExpr_I64 : i64 -> types_ConstExpr_t
| Types_ConstExpr_F32 : u32 -> types_ConstExpr_t
| Types_ConstExpr_F64 : u64 -> types_ConstExpr_t
| Types_ConstExpr_GlobalGet : u32 -> types_ConstExpr_t
.

(** [veriwasm::types::Mut]
    Source: 'src/types.rs', lines 38:0-41:1 *)
Inductive types_Mut_t :=
| Types_Mut_Const : types_Mut_t
| Types_Mut_Var : types_Mut_t
.

(** [veriwasm::types::ValueType]
    Source: 'src/types.rs', lines 14:0-19:1 *)
Inductive types_ValueType_t :=
| Types_ValueType_I32 : types_ValueType_t
| Types_ValueType_I64 : types_ValueType_t
| Types_ValueType_F32 : types_ValueType_t
| Types_ValueType_F64 : types_ValueType_t
.

(** [veriwasm::types::GlobalType]
    Source: 'src/types.rs', lines 88:0-91:1 *)
Record types_GlobalType_t :=
mktypes_GlobalType_t {
  types_GlobalType_mutability : types_Mut_t;
  types_GlobalType_valtype : types_ValueType_t;
}
.

(** [veriwasm::env::Global]
    Source: 'src/env.rs', lines 20:0-23:1 *)
Record env_Global_t :=
mkenv_Global_t {
  env_Global_gtype : types_GlobalType_t; env_Global_init : types_ConstExpr_t;
}
.

(** [veriwasm::types::ElemType]
    Source: 'src/types.rs', lines 73:0-75:1 *)
Inductive types_ElemType_t := | Types_ElemType_FuncRef : types_ElemType_t.

(** [veriwasm::limits::Limits]
    Source: 'src/limits.rs', lines 63:0-66:1 *)
Record limits_Limits_t :=
mklimits_Limits_t {
  limits_Limits_min : u32; limits_Limits_max : option u32;
}
.

(** [veriwasm::types::TableType]
    Source: 'src/types.rs', lines 80:0-83:1 *)
Record types_TableType_t :=
mktypes_TableType_t {
  types_TableType_limits : limits_Limits_t;
  types_TableType_elem : types_ElemType_t;
}
.

(** [veriwasm::types::MemType]
    Source: 'src/types.rs', lines 66:0-68:1 *)
Record types_MemType_t :=
mktypes_MemType_t {
  types_MemType_limits : limits_Limits_t;
}
.

(** [veriwasm::env::ImportDesc]
    Source: 'src/env.rs', lines 28:0-33:1 *)
Inductive env_ImportDesc_t :=
| Env_ImportDesc_Func : u32 -> env_ImportDesc_t
| Env_ImportDesc_Table : types_TableType_t -> env_ImportDesc_t
| Env_ImportDesc_Memory : types_MemType_t -> env_ImportDesc_t
| Env_ImportDesc_Global : types_GlobalType_t -> env_ImportDesc_t
.

(** [veriwasm::env::Import]
    Source: 'src/env.rs', lines 40:0-44:1 *)
Record env_Import_t :=
mkenv_Import_t {
  env_Import_module : alloc_vec_Vec u8;
  env_Import_name : alloc_vec_Vec u8;
  env_Import_desc : env_ImportDesc_t;
}
.

(** [veriwasm::env::ExportDesc]
    Source: 'src/env.rs', lines 49:0-54:1 *)
Inductive env_ExportDesc_t :=
| Env_ExportDesc_Func : u32 -> env_ExportDesc_t
| Env_ExportDesc_Table : u32 -> env_ExportDesc_t
| Env_ExportDesc_Memory : u32 -> env_ExportDesc_t
| Env_ExportDesc_Global : u32 -> env_ExportDesc_t
.

(** [veriwasm::env::Export]
    Source: 'src/env.rs', lines 59:0-62:1 *)
Record env_Export_t :=
mkenv_Export_t {
  env_Export_name : alloc_vec_Vec u8; env_Export_desc : env_ExportDesc_t;
}
.

(** [veriwasm::env::Element]
    Source: 'src/env.rs', lines 67:0-71:1 *)
Record env_Element_t :=
mkenv_Element_t {
  env_Element_table_idx : u32;
  env_Element_offset : types_ConstExpr_t;
  env_Element_init : alloc_vec_Vec u32;
}
.

(** [veriwasm::types::FuncType]
    Source: 'src/types.rs', lines 58:0-61:1 *)
Record types_FuncType_t :=
mktypes_FuncType_t {
  types_FuncType_params : alloc_vec_Vec types_ValueType_t;
  types_FuncType_results : alloc_vec_Vec types_ValueType_t;
}
.

(** [veriwasm::env::Env]
    Source: 'src/env.rs', lines 81:0-113:1 *)
Record env_Env_t :=
mkenv_Env_t {
  env_Env_types : alloc_vec_Vec types_FuncType_t;
  env_Env_imports : alloc_vec_Vec env_Import_t;
  env_Env_globals : alloc_vec_Vec env_Global_t;
  env_Env_exports : alloc_vec_Vec env_Export_t;
  env_Env_elements : alloc_vec_Vec env_Element_t;
  env_Env_start : option u32;
  env_Env_func_type_indices : alloc_vec_Vec u32;
  env_Env_func_types : alloc_vec_Vec types_FuncType_t;
  env_Env_table_types : alloc_vec_Vec types_TableType_t;
  env_Env_mem_types : alloc_vec_Vec types_MemType_t;
  env_Env_global_types : alloc_vec_Vec types_GlobalType_t;
  env_Env_num_imported_funcs : usize;
  env_Env_num_imported_globals : usize;
}
.

(** [veriwasm::error::VisitError]
    Source: 'src/error.rs', lines 51:0-53:1 *)
Inductive error_VisitError_t :=
| Error_VisitError_OutOfMemory : error_VisitError_t
.

(** [veriwasm::error::OpError]
    Source: 'src/error.rs', lines 19:0-46:1 *)
Inductive error_OpError_t :=
| Error_OpError_UnexpectedEof : error_OpError_t
| Error_OpError_LebTooLong : error_OpError_t
| Error_OpError_UnrecognizedOpcode : error_OpError_t
| Error_OpError_InvalidBlockType : error_OpError_t
| Error_OpError_TypeMismatch : error_OpError_t
| Error_OpError_EmptyStack : error_OpError_t
| Error_OpError_StackMismatch : error_OpError_t
| Error_OpError_UnknownLabel : error_OpError_t
| Error_OpError_UnknownLocal : error_OpError_t
| Error_OpError_UnknownGlobal : error_OpError_t
| Error_OpError_ImmutableGlobal : error_OpError_t
| Error_OpError_UnknownMemory : error_OpError_t
| Error_OpError_UnknownFunc : error_OpError_t
| Error_OpError_UnknownType : error_OpError_t
| Error_OpError_UnknownTable : error_OpError_t
| Error_OpError_TooManyResults : error_OpError_t
| Error_OpError_ReservedByteNotZero : error_OpError_t
| Error_OpError_InvalidAlignment : error_OpError_t
| Error_OpError_TrailingBytes : error_OpError_t
| Error_OpError_BodyTooLarge : error_OpError_t
| Error_OpError_Visitor : error_VisitError_t -> error_OpError_t
.

(** [veriwasm::error::Error]
    Source: 'src/error.rs', lines 58:0-110:1 *)
Inductive error_Error_t :=
| Error_Error_Read : error_OpError_t -> error_Error_t
| Error_Error_InvalidMagic : error_Error_t
| Error_Error_InvalidVersion : error_Error_t
| Error_Error_UnexpectedEof : error_Error_t
| Error_Error_InvalidType : u8 -> error_Error_t
| Error_Error_UnknownSection : u8 -> error_Error_t
| Error_Error_SectionOutOfOrder : error_Error_t
| Error_Error_SectionSizeMismatch : error_Error_t
| Error_Error_FuncCodeMismatch : error_Error_t
| Error_Error_MissingCodeSection : error_Error_t
| Error_Error_InvalidUtf8 : error_Error_t
| Error_Error_UnknownType : u32 -> error_Error_t
| Error_Error_UnknownFunc : u32 -> error_Error_t
| Error_Error_UnknownTable : u32 -> error_Error_t
| Error_Error_UnknownMemory : u32 -> error_Error_t
| Error_Error_UnknownGlobal : u32 -> error_Error_t
| Error_Error_DuplicateExportName : error_Error_t
| Error_Error_LimitsOutOfRange : error_Error_t
| Error_Error_MultipleMemories : error_Error_t
| Error_Error_MultipleTables : error_Error_t
| Error_Error_InvalidStartType : error_Error_t
| Error_Error_MutableGlobalInConstExpr : error_Error_t
| Error_Error_InvalidConstExpr : error_Error_t
| Error_Error_TooManyResults : error_Error_t
| Error_Error_TooManyLocals : error_Error_t
| Error_Error_ModuleTooLarge : error_Error_t
| Error_Error_Body : error_OpError_t -> error_Error_t
| Error_Error_Visitor : error_VisitError_t -> error_Error_t
.

(** [veriwasm::module::Data]
    Source: 'src/module.rs', lines 54:0-58:1 *)
Record module_Data_t :=
mkmodule_Data_t {
  module_Data_memory_idx : u32;
  module_Data_offset : types_ConstExpr_t;
  module_Data_init : alloc_vec_Vec u8;
}
.

(** [veriwasm::module::Tail]
    Source: 'src/module.rs', lines 62:0-64:1 *)
Record module_Tail_t :=
mkmodule_Tail_t {
  module_Tail_data : alloc_vec_Vec module_Data_t;
}
.

(** [veriwasm::module::ValidatedModule]
    Source: 'src/module.rs', lines 68:0-71:1 *)
Record module_ValidatedModule_t :=
mkmodule_ValidatedModule_t {
  module_ValidatedModule_env : env_Env_t;
  module_ValidatedModule_tail : module_Tail_t;
}
.

(** Trait declaration: [veriwasm::module::CodeVisitor]
    Source: 'src/module.rs', lines 1454:0-1490:1 *)
Record module_CodeVisitor_t (Self : Type) := mkmodule_CodeVisitor_t {
  module_CodeVisitor_t_on_need_bytes : Self -> usize -> result
    ((core_result_Result_t unit error_Error_t) * Self);
  module_CodeVisitor_t_on_code_entry : Self -> slice u8 -> env_Env_t -> usize
    -> usize -> usize -> usize -> result ((core_result_Result_t unit
    error_Error_t) * Self);
}.

Arguments mkmodule_CodeVisitor_t { _ }.
Arguments module_CodeVisitor_t_on_need_bytes { _ } _.
Arguments module_CodeVisitor_t_on_code_entry { _ } _.

(** [veriwasm::types::CustomSection]
    Source: 'src/types.rs', lines 131:0-142:1 *)
Record types_CustomSection_t :=
mktypes_CustomSection_t {
  types_CustomSection_name_len : usize;
  types_CustomSection_payload_start : usize;
  types_CustomSection_payload_end : usize;
}
.

(** Trait declaration: [veriwasm::module::ModuleVisitor]
    Source: 'src/module.rs', lines 1401:0-1411:1 *)
Record module_ModuleVisitor_t (Self : Type) := mkmodule_ModuleVisitor_t {
  module_ModuleVisitor_t_on_custom_section : Self -> types_CustomSection_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
}.

Arguments mkmodule_ModuleVisitor_t { _ }.
Arguments module_ModuleVisitor_t_on_custom_section { _ } _.

(** [veriwasm::module::CodeSection]
    Source: 'src/module.rs', lines 1151:0-1160:1 *)
Record module_CodeSection_t :=
mkmodule_CodeSection_t {
  module_CodeSection_count : u32;
  module_CodeSection_entries : usize;
  module_CodeSection_end : usize;
}
.

(** [veriwasm::visit::NopVisitor]
    Source: 'src/visit.rs', lines 413:0-413:22 *)
Definition visit_NopVisitor_t : Type := unit.

(** [veriwasm::opiter::LabelKind]
    Source: 'src/opiter.rs', lines 106:0-112:1 *)
Inductive opiter_LabelKind_t :=
| Opiter_LabelKind_Body : opiter_LabelKind_t
| Opiter_LabelKind_Block : opiter_LabelKind_t
| Opiter_LabelKind_Loop : opiter_LabelKind_t
| Opiter_LabelKind_Then : opiter_LabelKind_t
| Opiter_LabelKind_Else : opiter_LabelKind_t
.

(** [veriwasm::opiter::BlockType]
    Source: 'src/opiter.rs', lines 36:0-39:1 *)
Inductive opiter_BlockType_t :=
| Opiter_BlockType_Empty : opiter_BlockType_t
| Opiter_BlockType_Value : types_ValueType_t -> opiter_BlockType_t
.

(** [veriwasm::opiter::Ctrl]
    Source: 'src/opiter.rs', lines 117:0-124:1 *)
Record opiter_Ctrl_t :=
mkopiter_Ctrl_t {
  opiter_Ctrl_kind : opiter_LabelKind_t;
  opiter_Ctrl_block_type : opiter_BlockType_t;
  opiter_Ctrl_value_stack_base : usize;
  opiter_Ctrl_polymorphic_base : bool;
}
.

(** [veriwasm::opiter::StackType]
    Source: 'src/opiter.rs', lines 97:0-100:1 *)
Inductive opiter_StackType_t :=
| Opiter_StackType_Val : types_ValueType_t -> opiter_StackType_t
| Opiter_StackType_Bot : opiter_StackType_t
.

(** [veriwasm::opiter::OpIterState]
    Source: 'src/opiter.rs', lines 129:0-133:1 *)
Record opiter_OpIterState_t :=
mkopiter_OpIterState_t {
  opiter_OpIterState_vals : alloc_vec_Vec opiter_StackType_t;
  opiter_OpIterState_ctrls : alloc_vec_Vec opiter_Ctrl_t;
  opiter_OpIterState_pos : usize;
}
.

(** [veriwasm::opiter::MemArg]
    Source: 'src/opiter.rs', lines 56:0-59:1 *)
Record opiter_MemArg_t :=
mkopiter_MemArg_t {
  opiter_MemArg_align : u32; opiter_MemArg_offset : u32;
}
.

(** [veriwasm::opiter::Context]
    Source: 'src/opiter.rs', lines 70:0-74:1 *)
Record opiter_Context_t :=
mkopiter_Context_t {
  opiter_Context_locals : alloc_vec_Vec types_ValueType_t;
  opiter_Context_results : alloc_vec_Vec types_ValueType_t;
}
.

(** Trait declaration: [veriwasm::visit::OpVisitor]
    Source: 'src/visit.rs', lines 234:0-409:1 *)
Record visit_OpVisitor_t (Self : Type) := mkvisit_OpVisitor_t {
  visit_OpVisitor_t_on_function_start : Self -> opiter_Context_t -> u32 ->
    usize -> usize -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_unreachable : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_nop : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_block : Self -> opiter_OpIterState_t ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_loop : Self -> opiter_OpIterState_t ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_if : Self -> opiter_OpIterState_t -> opiter_BlockType_t
    -> result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_else : Self -> opiter_OpIterState_t ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_end : Self -> opiter_OpIterState_t -> opiter_LabelKind_t
    -> opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_br : Self -> opiter_OpIterState_t -> u32 ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_br_if : Self -> opiter_OpIterState_t -> u32 ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_br_table_label : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_br_table : Self -> opiter_OpIterState_t -> u32 ->
    opiter_BlockType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_return : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_call : Self -> opiter_OpIterState_t -> u32 -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_call_indirect : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_drop : Self -> opiter_OpIterState_t ->
    opiter_StackType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_select : Self -> opiter_OpIterState_t ->
    opiter_StackType_t -> result ((core_result_Result_t unit
    error_VisitError_t) * Self);
  visit_OpVisitor_t_on_local_get : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_local_set : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_local_tee : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_global_get : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_global_set : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_memory_size : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_memory_grow : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_const : Self -> opiter_OpIterState_t -> i32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_const : Self -> opiter_OpIterState_t -> i64 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_const : Self -> opiter_OpIterState_t -> u32 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_const : Self -> opiter_OpIterState_t -> u64 ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_load : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_f32_load : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_f64_load : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_load8_s : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_load8_u : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_load16_s : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_load16_u : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load8_s : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load8_u : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load16_s : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load16_u : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load32_s : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_load32_u : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_store : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_store : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_f32_store : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_f64_store : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_store8 : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_store16 : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_store8 : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_store16 : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i64_store32 : Self -> opiter_OpIterState_t ->
    opiter_MemArg_t -> result ((core_result_Result_t unit error_VisitError_t) *
    Self);
  visit_OpVisitor_t_on_i32_eqz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_eq : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_ne : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_lt_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_lt_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_gt_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_gt_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_le_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_le_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_ge_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_ge_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_eqz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_eq : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_ne : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_lt_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_lt_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_gt_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_gt_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_le_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_le_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_ge_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_ge_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_eq : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_ne : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_lt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_gt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_le : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_ge : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_eq : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_ne : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_lt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_gt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_le : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_ge : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_sub : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_mul : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_div_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_div_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_rem_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_rem_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_and : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_or : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_xor : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_shl : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_shr_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_shr_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_rotl : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_rotr : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_add : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_sub : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_mul : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_div_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_div_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_rem_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_rem_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_and : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_or : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_xor : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_shl : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_shr_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_shr_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_rotl : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_rotr : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_add : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_sub : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_mul : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_div : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_min : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_max : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_copysign : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_add : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_sub : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_mul : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_div : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_min : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_max : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_copysign : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_clz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_ctz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_popcnt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_add : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_clz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_ctz : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_popcnt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_abs : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_neg : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_ceil : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_floor : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_trunc : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_nearest : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_sqrt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_abs : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_neg : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_ceil : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_floor : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_trunc : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_nearest : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_sqrt : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_wrap_i64 : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_trunc_f32_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_trunc_f32_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_trunc_f64_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_trunc_f64_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_extend_i32_s : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_extend_i32_u : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_trunc_f32_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_trunc_f32_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_trunc_f64_s : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_trunc_f64_u : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_convert_i32_s : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_convert_i32_u : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_convert_i64_s : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_convert_i64_u : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_demote_f64 : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_convert_i32_s : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_convert_i32_u : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_convert_i64_s : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_convert_i64_u : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_promote_f32 : Self -> opiter_OpIterState_t -> result
    ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i32_reinterpret_f32 : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_i64_reinterpret_f64 : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f32_reinterpret_i32 : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
  visit_OpVisitor_t_on_f64_reinterpret_i64 : Self -> opiter_OpIterState_t ->
    result ((core_result_Result_t unit error_VisitError_t) * Self);
}.

Arguments mkvisit_OpVisitor_t { _ }.
Arguments visit_OpVisitor_t_on_function_start { _ } _.
Arguments visit_OpVisitor_t_on_unreachable { _ } _.
Arguments visit_OpVisitor_t_on_nop { _ } _.
Arguments visit_OpVisitor_t_on_block { _ } _.
Arguments visit_OpVisitor_t_on_loop { _ } _.
Arguments visit_OpVisitor_t_on_if { _ } _.
Arguments visit_OpVisitor_t_on_else { _ } _.
Arguments visit_OpVisitor_t_on_end { _ } _.
Arguments visit_OpVisitor_t_on_br { _ } _.
Arguments visit_OpVisitor_t_on_br_if { _ } _.
Arguments visit_OpVisitor_t_on_br_table_label { _ } _.
Arguments visit_OpVisitor_t_on_br_table { _ } _.
Arguments visit_OpVisitor_t_on_return { _ } _.
Arguments visit_OpVisitor_t_on_call { _ } _.
Arguments visit_OpVisitor_t_on_call_indirect { _ } _.
Arguments visit_OpVisitor_t_on_drop { _ } _.
Arguments visit_OpVisitor_t_on_select { _ } _.
Arguments visit_OpVisitor_t_on_local_get { _ } _.
Arguments visit_OpVisitor_t_on_local_set { _ } _.
Arguments visit_OpVisitor_t_on_local_tee { _ } _.
Arguments visit_OpVisitor_t_on_global_get { _ } _.
Arguments visit_OpVisitor_t_on_global_set { _ } _.
Arguments visit_OpVisitor_t_on_memory_size { _ } _.
Arguments visit_OpVisitor_t_on_memory_grow { _ } _.
Arguments visit_OpVisitor_t_on_i32_const { _ } _.
Arguments visit_OpVisitor_t_on_i64_const { _ } _.
Arguments visit_OpVisitor_t_on_f32_const { _ } _.
Arguments visit_OpVisitor_t_on_f64_const { _ } _.
Arguments visit_OpVisitor_t_on_i32_load { _ } _.
Arguments visit_OpVisitor_t_on_i64_load { _ } _.
Arguments visit_OpVisitor_t_on_f32_load { _ } _.
Arguments visit_OpVisitor_t_on_f64_load { _ } _.
Arguments visit_OpVisitor_t_on_i32_load8_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_load8_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_load16_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_load16_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_load8_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_load8_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_load16_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_load16_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_load32_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_load32_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_store { _ } _.
Arguments visit_OpVisitor_t_on_i64_store { _ } _.
Arguments visit_OpVisitor_t_on_f32_store { _ } _.
Arguments visit_OpVisitor_t_on_f64_store { _ } _.
Arguments visit_OpVisitor_t_on_i32_store8 { _ } _.
Arguments visit_OpVisitor_t_on_i32_store16 { _ } _.
Arguments visit_OpVisitor_t_on_i64_store8 { _ } _.
Arguments visit_OpVisitor_t_on_i64_store16 { _ } _.
Arguments visit_OpVisitor_t_on_i64_store32 { _ } _.
Arguments visit_OpVisitor_t_on_i32_eqz { _ } _.
Arguments visit_OpVisitor_t_on_i32_eq { _ } _.
Arguments visit_OpVisitor_t_on_i32_ne { _ } _.
Arguments visit_OpVisitor_t_on_i32_lt_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_lt_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_gt_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_gt_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_le_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_le_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_ge_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_ge_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_eqz { _ } _.
Arguments visit_OpVisitor_t_on_i64_eq { _ } _.
Arguments visit_OpVisitor_t_on_i64_ne { _ } _.
Arguments visit_OpVisitor_t_on_i64_lt_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_lt_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_gt_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_gt_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_le_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_le_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_ge_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_ge_u { _ } _.
Arguments visit_OpVisitor_t_on_f32_eq { _ } _.
Arguments visit_OpVisitor_t_on_f32_ne { _ } _.
Arguments visit_OpVisitor_t_on_f32_lt { _ } _.
Arguments visit_OpVisitor_t_on_f32_gt { _ } _.
Arguments visit_OpVisitor_t_on_f32_le { _ } _.
Arguments visit_OpVisitor_t_on_f32_ge { _ } _.
Arguments visit_OpVisitor_t_on_f64_eq { _ } _.
Arguments visit_OpVisitor_t_on_f64_ne { _ } _.
Arguments visit_OpVisitor_t_on_f64_lt { _ } _.
Arguments visit_OpVisitor_t_on_f64_gt { _ } _.
Arguments visit_OpVisitor_t_on_f64_le { _ } _.
Arguments visit_OpVisitor_t_on_f64_ge { _ } _.
Arguments visit_OpVisitor_t_on_i32_sub { _ } _.
Arguments visit_OpVisitor_t_on_i32_mul { _ } _.
Arguments visit_OpVisitor_t_on_i32_div_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_div_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_rem_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_rem_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_and { _ } _.
Arguments visit_OpVisitor_t_on_i32_or { _ } _.
Arguments visit_OpVisitor_t_on_i32_xor { _ } _.
Arguments visit_OpVisitor_t_on_i32_shl { _ } _.
Arguments visit_OpVisitor_t_on_i32_shr_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_shr_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_rotl { _ } _.
Arguments visit_OpVisitor_t_on_i32_rotr { _ } _.
Arguments visit_OpVisitor_t_on_i64_add { _ } _.
Arguments visit_OpVisitor_t_on_i64_sub { _ } _.
Arguments visit_OpVisitor_t_on_i64_mul { _ } _.
Arguments visit_OpVisitor_t_on_i64_div_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_div_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_rem_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_rem_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_and { _ } _.
Arguments visit_OpVisitor_t_on_i64_or { _ } _.
Arguments visit_OpVisitor_t_on_i64_xor { _ } _.
Arguments visit_OpVisitor_t_on_i64_shl { _ } _.
Arguments visit_OpVisitor_t_on_i64_shr_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_shr_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_rotl { _ } _.
Arguments visit_OpVisitor_t_on_i64_rotr { _ } _.
Arguments visit_OpVisitor_t_on_f32_add { _ } _.
Arguments visit_OpVisitor_t_on_f32_sub { _ } _.
Arguments visit_OpVisitor_t_on_f32_mul { _ } _.
Arguments visit_OpVisitor_t_on_f32_div { _ } _.
Arguments visit_OpVisitor_t_on_f32_min { _ } _.
Arguments visit_OpVisitor_t_on_f32_max { _ } _.
Arguments visit_OpVisitor_t_on_f32_copysign { _ } _.
Arguments visit_OpVisitor_t_on_f64_add { _ } _.
Arguments visit_OpVisitor_t_on_f64_sub { _ } _.
Arguments visit_OpVisitor_t_on_f64_mul { _ } _.
Arguments visit_OpVisitor_t_on_f64_div { _ } _.
Arguments visit_OpVisitor_t_on_f64_min { _ } _.
Arguments visit_OpVisitor_t_on_f64_max { _ } _.
Arguments visit_OpVisitor_t_on_f64_copysign { _ } _.
Arguments visit_OpVisitor_t_on_i32_clz { _ } _.
Arguments visit_OpVisitor_t_on_i32_ctz { _ } _.
Arguments visit_OpVisitor_t_on_i32_popcnt { _ } _.
Arguments visit_OpVisitor_t_on_i32_add { _ } _.
Arguments visit_OpVisitor_t_on_i64_clz { _ } _.
Arguments visit_OpVisitor_t_on_i64_ctz { _ } _.
Arguments visit_OpVisitor_t_on_i64_popcnt { _ } _.
Arguments visit_OpVisitor_t_on_f32_abs { _ } _.
Arguments visit_OpVisitor_t_on_f32_neg { _ } _.
Arguments visit_OpVisitor_t_on_f32_ceil { _ } _.
Arguments visit_OpVisitor_t_on_f32_floor { _ } _.
Arguments visit_OpVisitor_t_on_f32_trunc { _ } _.
Arguments visit_OpVisitor_t_on_f32_nearest { _ } _.
Arguments visit_OpVisitor_t_on_f32_sqrt { _ } _.
Arguments visit_OpVisitor_t_on_f64_abs { _ } _.
Arguments visit_OpVisitor_t_on_f64_neg { _ } _.
Arguments visit_OpVisitor_t_on_f64_ceil { _ } _.
Arguments visit_OpVisitor_t_on_f64_floor { _ } _.
Arguments visit_OpVisitor_t_on_f64_trunc { _ } _.
Arguments visit_OpVisitor_t_on_f64_nearest { _ } _.
Arguments visit_OpVisitor_t_on_f64_sqrt { _ } _.
Arguments visit_OpVisitor_t_on_i32_wrap_i64 { _ } _.
Arguments visit_OpVisitor_t_on_i32_trunc_f32_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_trunc_f32_u { _ } _.
Arguments visit_OpVisitor_t_on_i32_trunc_f64_s { _ } _.
Arguments visit_OpVisitor_t_on_i32_trunc_f64_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_extend_i32_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_extend_i32_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_trunc_f32_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_trunc_f32_u { _ } _.
Arguments visit_OpVisitor_t_on_i64_trunc_f64_s { _ } _.
Arguments visit_OpVisitor_t_on_i64_trunc_f64_u { _ } _.
Arguments visit_OpVisitor_t_on_f32_convert_i32_s { _ } _.
Arguments visit_OpVisitor_t_on_f32_convert_i32_u { _ } _.
Arguments visit_OpVisitor_t_on_f32_convert_i64_s { _ } _.
Arguments visit_OpVisitor_t_on_f32_convert_i64_u { _ } _.
Arguments visit_OpVisitor_t_on_f32_demote_f64 { _ } _.
Arguments visit_OpVisitor_t_on_f64_convert_i32_s { _ } _.
Arguments visit_OpVisitor_t_on_f64_convert_i32_u { _ } _.
Arguments visit_OpVisitor_t_on_f64_convert_i64_s { _ } _.
Arguments visit_OpVisitor_t_on_f64_convert_i64_u { _ } _.
Arguments visit_OpVisitor_t_on_f64_promote_f32 { _ } _.
Arguments visit_OpVisitor_t_on_i32_reinterpret_f32 { _ } _.
Arguments visit_OpVisitor_t_on_i64_reinterpret_f64 { _ } _.
Arguments visit_OpVisitor_t_on_f32_reinterpret_i32 { _ } _.
Arguments visit_OpVisitor_t_on_f64_reinterpret_i64 { _ } _.

(** [veriwasm::module::NopModuleVisitor]
    Source: 'src/module.rs', lines 1416:0-1416:28 *)
Definition module_NopModuleVisitor_t : Type := unit.

(** [veriwasm::module::ValidatingCodeVisitor]
    Source: 'src/module.rs', lines 1497:0-1497:33 *)
Definition module_ValidatingCodeVisitor_t : Type := unit.

(** [veriwasm::types::ExternType]
    Source: 'src/types.rs', lines 96:0-101:1 *)
Inductive types_ExternType_t :=
| Types_ExternType_Func : types_FuncType_t -> types_ExternType_t
| Types_ExternType_Table : types_TableType_t -> types_ExternType_t
| Types_ExternType_Memory : types_MemType_t -> types_ExternType_t
| Types_ExternType_Global : types_GlobalType_t -> types_ExternType_t
.

End Veriwasm_Types.
